# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a0554576184acd35f0551ba0943b15289398ca9ecd093abbed1f240fbe37797e9eb54c5cc8f49b19ecb91fc204efc284e2bd6b8c566d38c645453624d6d5582

test:
  secret_key_base: b458603d96c1e686816c556f81bacd35267e9f4f18883e63da1204832a59246910155c78a1433ee3026c5e6b86abf3987d6ef04e25501d20ab31e91c6aeb6a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
